server:
  port: 8443
  ssl:
    enabled: ${SSL_ENABLED:true}
    key-store: ${SSL_KEYSTORE:classpath:certs/ctf-local.p12}
    key-store-password: ${SSL_KEYSTORE_PASSWORD:}
    key-store-type: PKCS12
    key-alias: ${SSL_KEY_ALIAS:ctf-local}
  error:
    include-message: ${ERROR_MESSAGES:never}
logging:
  level:
    root: INFO
    org.springframework.security: DEBUG
    org.springframework: ERROR
    org.hibernate: ERROR
spring:
  config:
    import: classpath:config.yml
  security:
    debug: ${SPRING_SECURITY_DEBUG:false}
app:
  jwt:
    secret: ${JWT_SECRET:}
    expiry-minutes: 720 # 12 hours, should be enough
  security:
    public-paths:
      - /error
      - /game/health
      - /socket/**
      - /game/status
      - /game/settings
      - /player/join
      - /team/info/*
      - /api/push/**
    auth-pw: ${APP_AUTH_PASSWORD:}
    frontend: ${FRONTEND_URL:https://localhost:5173}
vapid:
  publicKey: ${VAPID_PUBLIC_KEY:}
  privateKey: ${VAPID_PRIVATE_KEY:}
  subject: ${VAPID_SUBJECT:mailto:example@mail.com}